# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

# We need to bump pip because the travis default version doesn't allow
#  dependency install via URL
before_install:
  - pip install --upgrade pip

install:
  - pip install -U tox-travis

# command to run tests, e.g. python setup.py test
script:
  - tox -e pylint

dist: xenial
